version: "3.8"

services:

    db:
        image: postgres
        container_name: postgres_db
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=mcs_db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=groot
    #        volumes:
    #            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pat@mat.com
            PGADMIN_DEFAULT_PASSWORD: groot
#        depends_on:
#            db:
#                condition: service_started

    consul:
        image: consul:1.15
        ports:
            - "8500:8500"
            - "8600:8600/udp"
        command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    
    consul-kv-init:
        image: bitsofinfo/files-to-consul-kv:1.0.6

        volumes:
            -   type: bind
                source: ./consul
                target: /kv-source

        # Usage: https://github.com/bitsofinfo/files-to-consul-kv
        command: "fs2consulkv.py -p /kv-source/properties -c http://consul:8500 -k config/ -t iamacl -s 1 --skip-prompt"
#        command: "sh /kv-source/init_kv.sh"

