version: "3.8"

services:

    db:
        image: postgres
        container_name: postgres_db
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: mcs_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: groot
    #       TODO uncomment once db data prepared
    #        volumes:
    #            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pat@mat.com
            PGADMIN_DEFAULT_PASSWORD: groot
        depends_on:
            db:
                condition: service_started


#   TODO postgres data: need entry data, setup accounts for each service, define structures, ...
#    volumes:
#        postgres_data: